# Generated by Django 5.1.4 on 2025-01-26 13:16

import core.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rescheduled', 'Rescheduled'), ('pending', 'Pending')], default=core.enums.MeetingStatus['PENDING'], max_length=20),
        ),
    ]
