# Generated by Django 4.2.18 on 2025-01-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_meeting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('cache_key', models.CharField(max_length=255)),
            ],
        ),
    ]
